[workspace]
members = [
    "crates/oxabl",
    "crates/oxabl_parser",
    "crates/oxabl_lexer",
    "crates/oxabl_common",
    "crates/oxabl_codegen",
    "crates/oxabl_ast",
    "crates/oxabl_workspace",
    "crates/oxabl_preprocessor",
    "crates/oxabl_schema",
    "crates/oxabl_semantic",
    "crates/oxabl_index",
    "crates/oxabl_lint",
    "crates/oxabl_analyze",
    "crates/oxabl_pipeline",
    "crates/oxabl_style",
    "crates/oxabl_daemon",
    "crates/oxabl_daemon_protocol",
    "crates/oxabl_lsp",
    "crates/oxabl_formatter",
    "crates/oxabl_wasm",
]
resolver = "2"
