// Generated by oxabl_codegen - DO NOT EDIT

//! Canonical (full-form) spelling of each abbreviable keyword `Kind`, used by
//! the keyword-abbreviation transform (U5) to expand an abbreviation to its
//! full ABL form. Generated from the same keyword source as the lexer's
//! `Kind` enum, so the two stay in lock-step (the plan's "reuse the lexer's
//! keyword knowledge" path).

use oxabl_lexer::Kind;

/// The canonical uppercase full-form spelling for an abbreviable keyword
/// `Kind`, or `None` for any kind that has no abbreviated form (punctuation,
/// operators, literals, identifiers, and preprocessor/include refs).
pub(crate) fn canonical_keyword(kind: Kind) -> Option<&'static str> {
    match kind {
        Kind::Accumulate => Some("ACCUMULATE"),
        Kind::Ambiguous => Some("AMBIGUOUS"),
        Kind::Analyze => Some("ANALYZE"),
        Kind::Ascending => Some("ASCENDING"),
        Kind::Available => Some("AVAILABLE"),
        Kind::Background => Some("BACKGROUND"),
        Kind::Centered => Some("CENTERED"),
        Kind::Cursor => Some("CURSOR"),
        Kind::Dbrestrictions => Some("DBRESTRICTIONS"),
        Kind::Dbversion => Some("DBVERSION"),
        Kind::Define => Some("DEFINE"),
        Kind::Delete => Some("DELETE"),
        Kind::Descending => Some("DESCENDING"),
        Kind::Dictionary => Some("DICTIONARY"),
        Kind::Disconnect => Some("DISCONNECT"),
        Kind::Display => Some("DISPLAY"),
        Kind::Fields => Some("FIELDS"),
        Kind::Format => Some("FORMAT"),
        Kind::Frame => Some("FRAME"),
        Kind::Gateways => Some("GATEWAYS"),
        Kind::Keyfunction => Some("KEYFUNCTION"),
        Kind::Listing => Some("LISTING"),
        Kind::Parameter => Some("PARAMETER"),
        Kind::Persistent => Some("PERSISTENT"),
        Kind::Preprocess => Some("PREPROCESS"),
        Kind::Proversion => Some("PROVERSION"),
        Kind::Rectangle => Some("RECTANGLE"),
        Kind::Setuserid => Some("SETUSERID"),
        Kind::Terminal => Some("TERMINAL"),
        Kind::Underline => Some("UNDERLINE"),
        Kind::Unformatted => Some("UNFORMATTED"),
        Kind::Modulo => Some("MODULO"),
        Kind::Initial => Some("INITIAL"),
        Kind::Integer => Some("INTEGER"),
        Kind::Decimal => Some("DECIMAL"),
        Kind::Character => Some("CHARACTER"),
        Kind::Logical => Some("LOGICAL"),
        Kind::Variable => Some("VARIABLE"),
        Kind::Compile => Some("COMPILE"),
        _ => None,
    }
}
