// Generated by oxabl_codegen - DO NOT EDIT

use crate::Kind;

/// Returns true if the given Kind can be used as a callable (function call position).
/// This includes user-defined identifiers and all built-in ABL functions.
///
/// # Example
/// ```ignore
/// // These are callable:
/// // - myFunction()     -> Kind::Identifier
/// // - NOW()            -> Kind::Now
/// // - TRIM(x)          -> Kind::Trim
/// ```
#[inline]
pub fn is_callable_kind(kind: Kind) -> bool {
    matches!(
        kind,
        Kind::Identifier
            | Kind::Accum
            | Kind::Alias
            | Kind::Cast
            | Kind::Chr
            | Kind::Connected
            | Kind::Dataservers
            | Kind::Dbcodepage
            | Kind::Dbcollation
            | Kind::Dbparam
            | Kind::Dbrestrictions
            | Kind::Dbtaskid
            | Kind::Dbtype
            | Kind::Dbversion
            | Kind::Encode
            | Kind::Etime
            | Kind::Fill
            | Kind::First
            | Kind::Gateways
            | Kind::Input
            | Kind::IsAttrSpace
            | Kind::IsLeadByte
            | Kind::Kblabel
            | Kind::Keycode
            | Kind::Keyfunction
            | Kind::Keylabel
            | Kind::Keyword
            | Kind::Last
            | Kind::LastOf
            | Kind::Lastkey
            | Kind::Ldbname
            | Kind::LineCounter
            | Kind::Lookup
            | Kind::Member
            | Kind::MessageLines
            | Kind::Now
            | Kind::NumAliases
            | Kind::NumDbs
            | Kind::Opsys
            | Kind::PageNumber
            | Kind::Pdbname
            | Kind::ProcHandle
            | Kind::ProcStatus
            | Kind::ProgramName
            | Kind::Progress
            | Kind::Proversion
            | Kind::RIndex
            | Kind::Retry
            | Kind::Sdbname
            | Kind::Search
            | Kind::Setuserid
            | Kind::Time
            | Kind::ToRowid
            | Kind::Trim
            | Kind::Userid
    )
}

/// List of all callable Kind variants (excluding Identifier).
/// Useful for documentation and testing.
pub const CALLABLE_FUNCTION_KINDS: &[Kind] = &[
    Kind::Accum,
    Kind::Alias,
    Kind::Cast,
    Kind::Chr,
    Kind::Connected,
    Kind::Dataservers,
    Kind::Dbcodepage,
    Kind::Dbcollation,
    Kind::Dbparam,
    Kind::Dbrestrictions,
    Kind::Dbtaskid,
    Kind::Dbtype,
    Kind::Dbversion,
    Kind::Encode,
    Kind::Etime,
    Kind::Fill,
    Kind::First,
    Kind::Gateways,
    Kind::Input,
    Kind::IsAttrSpace,
    Kind::IsLeadByte,
    Kind::Kblabel,
    Kind::Keycode,
    Kind::Keyfunction,
    Kind::Keylabel,
    Kind::Keyword,
    Kind::Last,
    Kind::LastOf,
    Kind::Lastkey,
    Kind::Ldbname,
    Kind::LineCounter,
    Kind::Lookup,
    Kind::Member,
    Kind::MessageLines,
    Kind::Now,
    Kind::NumAliases,
    Kind::NumDbs,
    Kind::Opsys,
    Kind::PageNumber,
    Kind::Pdbname,
    Kind::ProcHandle,
    Kind::ProcStatus,
    Kind::ProgramName,
    Kind::Progress,
    Kind::Proversion,
    Kind::RIndex,
    Kind::Retry,
    Kind::Sdbname,
    Kind::Search,
    Kind::Setuserid,
    Kind::Time,
    Kind::ToRowid,
    Kind::Trim,
    Kind::Userid,
];
