[package]
name = "oxabl_parser"
version = "0.4.0"
edition = "2024"
license = "MIT"
description = "Parser for Progress ABL source code"
repository = "https://github.com/oxabl-project/oxabl/crates/oxabl_parser"

[dependencies]
oxabl_ast = { path = "../oxabl_ast", version = "0.4.0" }
oxabl_lexer = { path = "../oxabl_lexer", version = "0.3.1" }
rust_decimal = "1.40.0"
